
language: swift
osx_image: xcode7.3
branches:
  only:
    - master
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:

  
- set -o pipefail
- xcodebuild -project "Example/Example.xcodeproj" -scheme "Example" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint --quick